Fix insecure links
google/leveldb pull request #862
Opened 2020-12-17 07:07 UTC by rex4539

2020-12-19 16:20 UTC, daira commented on table/format.h
> +//    echo https://github.com/google/leveldb | sha1sum
Revert this change; the hash depends on that specific URL.

2020-12-19 16:22 UTC, daira requested changes
I checked all of these URLs. The change to the SHA-1 hash input should be reverted.

2020-12-20 20:37 UTC, daira commented
Looks good to me.

2020-12-20 20:37 UTC, daira approved these changes

2020-12-31 01:20 UTC, pwnall approved these changes
LGTM. Thank you for your contributions!

We'll submit a change based on this PR to the internal repository. Your PR will be merged when the change is published.

2020-12-31 01:20 UTC, pwnall commented on doc/benchmark.html
> +<p>In order to test LevelDB's performance, we benchmark it against other well-established database implementations. We compare LevelDB (revision 39) against <a href="https://www.sqlite.org/">SQLite3<
Verified that `http://fallabs.com/kyotocabinet/spex.html` redirects to `https://dbmx.net/kyotocabinet/spex.html`.

2020-12-31 01:20 UTC, pwnall commented on doc/impl.md
> +single [Bigtable tablet (section 5.3)](https://research.google/pubs/pub27898/).
Verified that `http://research.google.com/archive/bigtable.html` redirects to `https://research.google/pubs/pub27898/`.

2021-01-01 09:32 UTC, merged

2021-11-12 16:24 UTC, q464pp commented
可以拉取合併嗎？謝謝